spring:
  application:
    name: eureka-server
server:
  port: 8761
#Eureka Server인데 Client 설정을 하는 이유:
#유레카 라이브러리가 포함돼있으면 스프링 실행 시 유레카 클라이언트의 역할로써 등록되기 때문에
#그렇기 때문에 서버이지만 클라이언트로 설정 정보를 관리할 수 있다.
eureka:
  client:
    register-with-eureka: false 	#유레카 레지스트리에 자기 자신을 등록하지 않겠다.
    fetch-registry: false   		#레지스트리의 정보를 가저오지 않겠다.