version: "3.9"
services:
  mysql-db:
    image: mysql:8.0.28
    container_name: mysql-db-container
    restart: always
    ports:
      - "3307:3306"	# mysql 기본 port
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: preorder	# database 이름
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
#    volumes:
#      - ./db/mysql/data:/var/lib/mysql
#      - ./db/mysql/config:/etc/mysql/conf.d
#      - ./db/mysql/init:/docker-entrypoint-initdb.d
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  springboot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: springboot-app
    ports:
      - "8070:8070"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db-container:3306/preorder
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql-db
      - redis











## 파일 규격 버전
#version: "3"
## 이 항목 밑에 실행하려는 컨테이너 들을 정의
#services:
#  # 서비스 명
#  db:
#    # 사용할 이미지
#    image: 6f343283ab56d883ec8ea17641b5d61d0252cc6c97dad3849cf3681dd1e2f37d
#    # 컨테이너 이름 설정
#    container_name: mysql-db-container
#    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
#    ports:
#      - "3307:3306"
#    # -e 옵션
#    environment:
#      # MYSQL 패스워드 설정 옵션
#      MYSQL_ROOT_PASSWORD: "1234"
#    # 명령어 실행 (한글 인코딩 관련)
##    command:
##      - --character-set-server=utf8mb4
##      - --collation-server=utf8mb4_unicode_ci
#      # -v 옵션 (다렉토리 마운트 설정)
##      - D:/docker/mysql/data:/var/lib/mysql
#
#
#  app:
#    container_name: jdk21
#    image: openjdk:21-jdk
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./app:/app
#    working_dir: /app
##    command: [“/build/gradlew”, “bootrun”]
#    depends_on:
#      - db
#    restart: always
#
#
#  spring:
#      build:
#        context: .
#      image: 4074e5e45c239771eca9d695031e13c14a249efa4b620d520dbef501ce23229c
#      container_name: docker-springboot-container
#      ports:
#        - "8090:8090"
#      volumes:
#        - "./data:/app/data"  # 선택적으로 로컬 디렉토리를 컨테이너와 연결
#      environment:
#        - SPRING_PROFILES_ACTIVE=prod
#        - JAVA_OPTS=-Xmx512m -Xms256m
#
#
#
#
##  volumes:
##    data:  # 선택적으로 정의된 볼륨