server:
  port: 8000
spring:
  application:
    name: spring-api-gateway
#  data:
#    redis:
#      host: localhost
#      port: 6379
  cloud:
    gateway:
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway Global Filter
#            preLogger: true
#            postLogger: true
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/member-service/**
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
#          filters: # 커스텀필터 적용
#            - CustomAuthFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product-service/** # 요기로 들어온 요청을 위에 uri로 보냄
          filters:                         #filters-> predicates의 Path를 바꿔서 보내줌
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
