DROP TABLE IF EXISTS ORDERS;

CREATE TABLE `ORDERS` (
     `ORDER_ID`	INT	NOT NULL,
     `PRODUCT_ID`	INT	NOT NULL,
     `PRODUCT_COUNT` INT NOT NULL,
     `MEMBER_ID`	INT	NOT NULL,
     `ORDER_ADDR`	VARCHAR(500)	NOT NULL,
     `ORDER_PHONE`	VARCHAR(100)	NOT NULL,
     `ORDER_MEMO`	VARCHAR(1000)	NULL,
     `ORDER_PRICE`	INT	NOT NULL,
     `ORDER_DATE`	DATE	NULL ,
     `ORDER_STATUS`	ENUM ('배송전', '배송중', '배송완료',
         '취소완료', '반품중', '반품완료') NULL DEFAULT '배송전'
);

ALTER TABLE ORDERS MODIFY ORDER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

DROP TABLE IF EXISTS ORDER_CANCEL;

CREATE TABLE `ORDER_CANCEL` (
		ORDER_ID INT NOT NULL,
		MEMBER_ID INT NOT NULL,
		PRODUCT_ID INT NOT NULL,
		OPTION_ID INT NOT NULL,
		CANCEL_DATE DATE NOT NULL,
		CANCEL_REASON VARCHAR(1000) NOT NULL
);


ALTER TABLE ORDER_CANCEL ADD CONSTRAINT PK_ORDER_CANCEL PRIMARY KEY (ORDER_ID);



DROP TABLE IF EXISTS WISHLIST;

CREATE TABLE `WISHLIST` (
    `WISH_ID`	INT	NOT NULL,
    `PRODUCT_ID`	INT	NOT NULL,
    `MEMBER_ID`	INT	NOT NULL,
    `OPTION_ID`	INT	NOT NULL,
    `PRODUCT_COUNT`	INT	NOT NULL
);


ALTER TABLE `WISHLIST` ADD CONSTRAINT `PK_WISHLIST` PRIMARY KEY (`WISH_ID`, `PRODUCT_ID`, `MEMBER_ID`);