DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE `PRODUCT` (
         `PRODUCT_ID`	INT	NOT NULL,
         `PRODUCT_NAME`	VARCHAR(500)	NOT NULL,
         `PRODUCT_PRICE`	INT	NOT NULL,
         `PRODUCT_STOCK`	INT	NOT NULL,
         `PRODUCT_DESCRIPTION`	VARCHAR(1000)	NULL,
         `PRODUCT_STATUS`	CHAR(1)	NOT NULL	DEFAULT 'Y'
);

ALTER TABLE `PRODUCT` ADD CONSTRAINT `PK_PRODUCT` PRIMARY KEY (`PRODUCT_ID`);