server:
  port: 8083
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/preorder
    username: admin
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registryFetchIntervalSeconds: 5
#    disable-delta: true
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defalutZone: http://localhost:8761/eureka